apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsdb
  namespace: exam-2
spec:
  replicas: 2
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
      - name: mysql
        image: cgironza/mysql:0.1.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MYSQL"
        - name: MYSQL_DATABASE
          value: "db_operation"

---
apiVersion: v1
kind: Service
metadata:
  name: cip
  namespace: exam-2
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    role: db